name: vuln

on:
  pull_request:
  workflow_dispatch:

jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - uses: go-task/setup-task@v2
      - run: task vuln
